name: Python Render Engine Serve

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Set up Python
            uses: actions/setup-python@v2
            with:
                python-version: '3.11'

        - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install src

        - name: Run Render Engine Serve
            run: |
                python -m render_engine serve --build docs:app
